import Head from 'next/head'

import AppNavBar from '../components/AppNavBar';
import AppCardBullets from '../components/AppCardBullets';

export default function Home() {

  let title = 'Meu Primeiro Web App';

  const bullets_today = [
    {type: 'evento', title: 'Momento síncrono sobre componente REACT '},
    {type: 'task', title: 'Palavras chaves - bullet journal, github issues'},
  ];
  const bullets = [
    {type: 'task', title: 'Priorizar as palavras-chaves'},
    {type: 'task', title: 'Pesquisar imagens a partir das principais palavras-chaves'},
    {type: 'task', title: 'Prototipar UI'},
  ];

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppNavBar title={title} />
        <AppCardBullets date={"15/09/2021"} bullets={bullets_today} />
        <AppCardBullets date={"22/09/2021"} bullets={bullets} />
      </main>
    </div>
  )
}
